# config/packages/vich_uploader.yaml
vich_uploader:
    db_driver: orm

    mappings:
        image:
            uri_prefix: '/img'
            upload_destination: '%kernel.project_dir%/public/img'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: false