<?php

namespace ContainerKqhNo7o;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ILXo7dService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.IL_xo7d' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.IL_xo7d'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'passwordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
            'request' => ['privates', '.errored..service_locator.IL_xo7d.Symfony\\Component\\BrowserKit\\Request', NULL, 'Cannot autowire service ".service_locator.IL_xo7d": it references class "Symfony\\Component\\BrowserKit\\Request" but no such service exists.'],
        ], [
            'doctrine' => '?',
            'passwordHasher' => '?',
            'request' => 'Symfony\\Component\\BrowserKit\\Request',
        ]);
    }
}
