<?php

namespace ContainerKqhNo7o;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPersoRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\PersoRepository' shared autowired service.
     *
     * @return \App\Repository\PersoRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\PersoRepository'] = new \App\Repository\PersoRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
