<?php

namespace ContainerKqhNo7o;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRequestService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.IL_xo7d.Symfony\Component\BrowserKit\Request' shared service.
     *
     * @return \Symfony\Component\BrowserKit\Request
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.IL_xo7d": it references class "Symfony\\Component\\BrowserKit\\Request" but no such service exists.');
    }
}
