<?php

namespace ContainerKqhNo7o;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getThemeRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\ThemeRepository' shared autowired service.
     *
     * @return \App\Repository\ThemeRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\ThemeRepository'] = new \App\Repository\ThemeRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
