<?php

namespace ContainerKqhNo7o;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getThemeService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.geHOOt8.App\Entity\Theme' shared service.
     *
     * @return \App\Entity\Theme
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.geHOOt8": it references class "App\\Entity\\Theme" but no such service exists.');
    }
}
