<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKqhNo7o\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKqhNo7o/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerKqhNo7o.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerKqhNo7o\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerKqhNo7o\App_KernelProdContainer([
    'container.build_hash' => 'KqhNo7o',
    'container.build_id' => '68a37cdb',
    'container.build_time' => 1647714404,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKqhNo7o');
