<?php

namespace ContainerA9xgCjH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GeHOOt8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.geHOOt8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.geHOOt8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'theme' => ['privates', '.errored..service_locator.geHOOt8.App\\Entity\\Theme', NULL, 'Cannot autowire service ".service_locator.geHOOt8": it references class "App\\Entity\\Theme" but no such service exists.'],
        ], [
            'theme' => 'App\\Entity\\Theme',
        ]);
    }
}
