<?php

namespace ContainerA9xgCjH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OkRH5CService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.okRH5C_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.okRH5C_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'themes' => ['privates', 'App\\Repository\\ThemeRepository', 'getThemeRepositoryService', true],
        ], [
            'themes' => 'App\\Repository\\ThemeRepository',
        ]);
    }
}
