<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerA9xgCjH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerA9xgCjH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerA9xgCjH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerA9xgCjH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerA9xgCjH\App_KernelDevDebugContainer([
    'container.build_hash' => 'A9xgCjH',
    'container.build_id' => '37f0eb35',
    'container.build_time' => 1648827327,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerA9xgCjH');
